listenat: :8888
syncer:
  mysqladdress: localhost:3306
  mysqluser: root
  mysqlpassword: root
  mysqltable: test.tdanmaku
  redisaddress: localhost:6379
  redispassword: ""
  flushintervalsecond: 2
  redisshufflesuffix: inprogress
  pubdanmakulistname: pub_danmaku_delta
  likedanmakuhashname: like_danmaku_delta
  dislikedanmakuhashname: dislike_danmaku_delta
  userlikesdanmakuhash: user_likes_danmaku

